import React, { useEffect, useRef, forwardRef } from "react";
import Chart from "chart.js/auto";

const ReportDocument = forwardRef(
    (
        {
            reportData,
            scale,
            auth,
            collegeName,
            collegeLogo,
            collegeColor,
            collegeEmail,
        },
        ref,
    ) => {
        const chartCanvasRef = useRef(null);
        const chartInstanceRef = useRef(null);

        // Isolate Chart.js Logic here
        useEffect(() => {
            if (reportData && chartCanvasRef.current) {
                if (chartInstanceRef.current) {
                    chartInstanceRef.current.destroy();
                }

                const ctx = chartCanvasRef.current.getContext("2d");

                chartInstanceRef.current = new Chart(ctx, {
                    type: reportData.chartType,
                    data: reportData.chartData,
                    options: {
                        responsive: true,
                        maintainAspectRatio: false,
                        animation: false, // Critical for PDF snapshots
                        plugins: {
                            legend: { display: true, position: "top" },
                        },
                        scales: {
                            y: { beginAtZero: true },
                        },
                    },
                });
            }

            return () => {
                if (chartInstanceRef.current)
                    chartInstanceRef.current.destroy();
            };
        }, [reportData]);

        return (
            <div
                id="report"
                ref={ref}
                style={{
                    transform: `scale(${scale})`,
                    transformOrigin: "top center",
                }}
                className="w-[816px] min-h-[1056px] bg-white p-12 shadow-[0_10px_40px_rgba(0,0,0,0.15)] box-border flex flex-col mx-auto"
            >
                <div className="flex-1">
                    {/* HEADER */}
                    <header className="flex justify-between items-start mb-8 border-b-2 border-gray-100 pb-6">
                        <img
                            src="/formal.webp"
                            alt="Formal Logo"
                            className="h-[90px] w-auto"
                        />
                        {collegeLogo && (
                            <img
                                src={collegeLogo}
                                alt="College Logo"
                                className="h-[100px] w-auto ml-auto object-contain"
                            />
                        )}
                    </header>

                    {/* CONTENT */}
                    <section className="mb-6">
                        <div className="mb-6">
                            <h1 className="font-serif text-3xl font-bold text-gray-900 mb-2 leading-tight">
                                {reportData.title}
                            </h1>
                            <div className="font-montserrat text-sm text-gray-500 mb-1">
                                <strong>Generated On:</strong>{" "}
                                {reportData.timestamp}
                            </div>
                            <div className="font-montserrat text-sm text-gray-500">
                                <strong>Generated By:</strong>{" "}
                                {auth?.user?.name || "System Administrator"}
                            </div>
                        </div>

                        <div className="font-serif text-lg text-gray-800 leading-relaxed text-justify mb-8">
                            {reportData.summary}
                        </div>

                        <div className="mt-8 border border-gray-200 rounded-xl p-6 bg-white shadow-sm">
                            <h2 className="font-montserrat font-bold text-[#5c297c] text-lg mb-6 text-center border-b border-gray-100 pb-3">
                                Data Visualization
                            </h2>
                            {/* CHART TARGET */}
                            <div className="h-[350px] w-full relative">
                                <canvas
                                    id="chartCanvas"
                                    ref={chartCanvasRef}
                                ></canvas>
                            </div>
                        </div>
                    </section>
                </div>

                {/* FOOTER */}
                <footer className="w-[calc(100%+6rem)] -ml-12 mt-12 flex border-t-[6px] border-[#ffb736]">
                    {collegeName && (
                        <div
                            className="text-white w-[40%] p-8 flex flex-col justify-center min-h-[140px]"
                            style={{
                                backgroundColor: collegeColor || "#930147",
                            }}
                        >
                            <div className="font-serif text-lg font-bold tracking-wide mb-1">
                                Manila Central University
                            </div>
                            <div className="font-serif text-base opacity-90 mb-1">
                                {collegeName}
                            </div>
                            <div className="font-serif text-sm opacity-80">
                                {collegeEmail}
                            </div>
                        </div>
                    )}

                    <div
                        className={`bg-[#5c297c] text-white p-8 flex justify-between items-center min-h-[140px] ${collegeName ? "w-[60%]" : "w-full"}`}
                    >
                        <div className="flex flex-col justify-center space-y-1.5">
                            <div className="font-serif text-sm opacity-90">
                                <i className="bi bi-geo-alt-fill mr-2"></i>{" "}
                                EDSA, Caloocan City 1400
                            </div>
                            <div className="font-serif text-sm opacity-90">
                                <i className="bi bi-telephone-fill mr-2"></i>{" "}
                                +63 2 8364-10-71 to 78
                            </div>
                            <div className="font-serif text-sm opacity-90">
                                <i className="bi bi-envelope-fill mr-2"></i>{" "}
                                hello@mcu.edu.ph
                            </div>
                        </div>

                        <div className="flex flex-col items-center">
                            <img
                                src="/qr.webp"
                                alt="QR Code"
                                className="w-20 h-20 object-contain bg-white p-1.5 rounded-lg mb-2 shadow-sm"
                            />
                            <div className="font-montserrat font-bold text-[11px] tracking-widest">
                                www.mcu.edu.ph
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        );
    },
);

export default ReportDocument;
